version: "1.0.0"
services:
  bot:
    depends_on:
      - db
    links:
      - db
    build: .

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: io
      POSTGRES_DB: io
      POSTGRES_PASSWORD: io
