version: "3.8"
services:
  bot:
    image: lunarmagpie/io:latest
    restart: always
    network_mode: bridge
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    network_mode: bridge
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: io
      POSTGRES_DB: io
      POSTGRES_PASSWORD: io

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval=7200

volumes:
  db-data:
    driver: local
